# Generated by Django 5.0.1 on 2026-09-25 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='deleted',
            new_name='deleted_at',
        ),
    ]
