# Generated by Django 5.0.1 on 2026-09-25 09:16

import apps.common.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankdocumentfile',
            old_name='deleted',
            new_name='deleted_at',
        ),
        migrations.AlterField(
            model_name='bankdocumentfile',
            name='file',
            field=models.FileField(max_length=500, upload_to=apps.common.models.base.UploadToFolder('bank_document_file')),
        ),
    ]
