# Generated by Django 5.0.1 on 2026-10-05 06:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_rename_deleted_bankdocumentfile_deleted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccountBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('bank_name', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('account_holder_name', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('account_number', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('ifsc', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('statement_period_start', models.DateField(blank=True, default=None, null=True)),
                ('statement_period_end', models.DateField(blank=True, default=None, null=True)),
                ('opening_balance', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=15, null=True)),
                ('closing_balance', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=15, null=True)),
                ('transaction_count', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('total_credit', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=15, null=True)),
                ('total_debit', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=15, null=True)),
                ('net_movement', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=15, null=True)),
                ('validations', models.JSONField(default=dict)),
                ('money_received', models.JSONField(default=list)),
                ('money_paid', models.JSONField(default=list)),
                ('category_breakdown', models.JSONField(default=dict)),
                ('counterparties', models.JSONField(default=list)),
                ('clusters', models.JSONField(default=list)),
                ('categories', models.JSONField(default=dict)),
                ('payment_modes', models.JSONField(default=dict)),
                ('monthly_trends', models.JSONField(default=dict)),
                ('unknown_transaction_ids', models.JSONField(default=list)),
                ('review_queue', models.JSONField(default=list)),
                ('warnings', models.JSONField(default=list)),
                ('model', models.CharField(blank=True, default='', max_length=512)),
                ('prompt_version', models.CharField(blank=True, default='', max_length=512)),
                ('transactions', models.JSONField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='deleted_by_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.bankdocumentfile')),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
