# Generated by Django 5.0.1 on 2026-10-07 12:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_bankaccountbase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualBankAccountBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('business_name', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('account_reference', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('business_type', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('statement_period', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('opening_balance', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=15, null=True)),
                ('closing_balance', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=15, null=True)),
                ('transactions', models.JSONField(default=list)),
                ('clusters', models.JSONField(default=list)),
                ('model', models.CharField(blank=True, default='', max_length=512)),
                ('prompt_version', models.CharField(blank=True, default='', max_length=512)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='deleted_by_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
